### ISSUE TITLE
В Queue не хватает метода для получения кол-ва задач в очереди.

### ISSUE THREAD

**Issue by butschster** [spiral/roadrunner-jobs#2]
Для полной совместимости в [Queue](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Contracts/Queue/Queue.php) интерфйесом Laravel не хватает данных для метода size. Заодно можно посмотреть и на другие методы, вдруг появится желание еще что нибудь добавить.

Кстати было бы удобно иметь метод getRpc или Call для осуществления кастомных запросов

**Comment by rustatian** [comment]
@butschster Please, recreate the issue in English
