### ISSUE TITLE
Reconnect Rabbit

### ISSUE THREAD

**Issue by Colomix** [spiral/roadrunner-jobs#40]
Hello! I have problem. When rabbitmq is restarted for some reason, services stop publishing messages to it. Log:

`
exited from redialer
publish channel close	{"error": "Exception (504) Reason: \"channel/connection is not open\""}
state channel close	{"error": "Exception (504) Reason: \"channel/connection is not open\""}
amqp connection closed	{"error": "Exception (504) Reason: \"channel/connection is not open\""}
pipeline connection was closed, redialing	{"error": "Exception (501) Reason: \"read tcp : i/o timeout\"", "pipeline": "aggregator-event", "driver": "amqp", "start": "2023-03-06T06:48:14.218Z"}
backoff operation failed	{"error": "rabbitmq_redial: dial tcp :5672: i/o timeout"}
`

I think, that module amqp does not reconnect to channel

**Comment by butschster** [comment]
@rustatian

**Comment by rustatian** [comment]
Hey guys 👋🏻 

@Colomix You need to increase a redial timeout: https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1335

**Comment by Kreczat** [comment]
Thanks for your advice about redial_timeout, but there's new problem. After the last retry attempt we see this message: `backoff operation failed	{"error": "rabbitmq_redial: Exception (404) Reason: \"NOT_FOUND - no queue 'default' in vhost 'our_vhost'\""}`.
Previous message was "rabbitmq dial was succeed. trying to redeclare queues and subscribers"

Our service uses no queues, it deals with exchange only: all necessary queues are bound to exchange by other services. So we don't need to redeclare any queues.
How to reconnect without queues correctly?

**Comment by rustatian** [comment]
Since all questions are resolved (waiting for the release), @butschster you may close this issue. Thanks.
