### ISSUE TITLE
[Bug][Job][ReceivedTask] Retry task dosent work properly

### ISSUE THREAD

**Issue by sergey-telpuk** [spiral/roadrunner-jobs#8]
Tasks cloning and responding destructor side effects.

Currently it seems to be impossible to setup retries using the docs recommended way(via headers).
We are working with \Spiral\RoadRunner\Jobs\Task\ReceivedTask objects.
Once you call 
$task->withHeader('retries', $x)
 to refresh the retries left, a copy of your task is created.
Now, take a look at __destruct():
```php
public function __destruct()
{
    try {
        if ($this->completed === null) {
            $this->complete();
        }
    } catch (JobsException $e) {
        // Suppress shutdown exception
    }
}
```
And $this->complete() call:
```php
public function complete(): void
{
    $this->respond(Type::SUCCESS);
}
```
Back to our code. Copy of a task means we will have 2 respond() calls,
one from originalTask::destruct() and one from our retry logic.
$task->fail('error message', $resend=true);

Even if you assign both task copies to delay the destruct() call of the original one:
$taskCopy = $task->withHeader('attempts', (string) $retries);

$taskCopy->fail('error message', $resend=true);
One of these will be called 
$task->complete()
 from __destruct()
or 
$task->fail($x, $y)
 manually.
And it will cause problems, breaking our resend flow.

**Comment by sergey-telpuk** [comment]
Any updates about this issue?

**Comment by butschster** [comment]
@sergey-telpuk Thank you for contribution!
